Pass `RTCIceCandidateInit` object directly to `addIceCandidate()`
The intermediate `RTCIceCandidate` object is unnecessary and seems to
cause the following error on Chrome 68 (released ~2.5 years ago) when
the end-of-candidates signal arrives:

    Error: Failed to construct 'RTCIceCandidate': The 'candidate'
    property is not a string, or is empty.
        at new RTCIceCandidate
        at Object.receiveMessage
        at Object.handleClientMessage_RTC_MESSAGE [as hook_fn]
        at callHookFnSync
        at hooks.map
        at Array.map
        at Object.exports.callAll
        at Object.handleMessageFromServer
        at r.socket.on
        at r.emit