Move `logErrorToServer()` out of the `ep_webrtc` object
This fixes a "TypeError: this.logErrorToServer is not a function"
error inside `PeerState` (introduced in commit
003b89859a61c4a2a71f0931cba37e56a0e4ee5e) when renegotiation is
required.